### ISSUE TITLE
it wont click

### ISSUE THREAD

**Issue by numbplat** [robiot/xclicker#100]
### ISSUE TYPE:
 - Bug Report

#### OS / ENVIRONMENT:
 * Operating system: Version 126.0.6478.222 (Official Build) (64-bit)
 * De or Wm: unsure
 * XClicker version: v1.5.1

#### STEPS TO REPRODUCE:
1. download xclicker_1.5.1_arm64.deb
2. right click and install with linux
3. open app and start

#### EXPECTED BEHAVIOUR:
 to start auto clicking 

#### ACTUAL BEHAVIOUR:
 started but did nothing

**Comment by robiot** [comment]
Are you on xorg or wayland. U need to be on xorg for it work.

**Comment by robiot** [comment]
No additional feedback provided. Closing issue
