### ISSUE TITLE
Does NOT Click at all with Hot Key OR Clicking Start

### ISSUE THREAD

**Issue by emahiser** [robiot/xclicker#101]
### ISSUE TYPE:
 - Bug Report

#### OS / ENVIRONMENT:
 * Operating system: Ubuntu
 * De or Wm:
 * XClicker version: [v1.5.1]

#### STEPS TO REPRODUCE:
1.
2.
3.

**Comment by LAZAR-code** [comment]
Can you please specify more info? De? Wm? Wayland or x11? The autoclicker does not work in wayland.

**Comment by emahiser** [comment]
It don't matter anymore, I Moved on to a different Auto Clicker that WORKS!

**Comment by chillinwithmao** [comment]
> It don't matter anymore, I Moved on to a different Auto Clicker that WORKS!

This is a 2 months old thread but can you tell me which clicker did you use, i need 1 for my wayland usage. Thx!
