### ISSUE TITLE
is not compiling

### ISSUE THREAD

**Issue by TTorai** [robiot/xclicker#102]
`x@y:~/development/temp$ git clone https://github.com/robiot/xclicker
Cloning into 'xclicker'...
remote: Enumerating objects: 1109, done.
remote: Counting objects: 100% (365/365), done.
remote: Compressing objects: 100% (188/188), done.
remote: Total 1109 (delta 212), reused 177 (delta 177), pack-reused 744 (from 1)
Receiving objects: 100% (1109/1109), 3.37 MiB | 5.59 MiB/s, done.
Resolving deltas: 100% (614/614), done.

x@y:~/development/temp$ cd xclicker/

x@y:~/development/temp/xclicker$ make release 
The Meson build system
Version: 0.53.2
Source dir: /home/m/development/temp/xclicker
Build dir: /home/m/development/temp/xclicker/build/release
Build type: native build
Project name: XClicker
Project version: undefined
C compiler for the host machine: cc (gcc 9.4.0 "cc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0")
C linker for the host machine: cc ld.bfd 2.34
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Run-time dependency gtk+-3.0 found: YES 3.24.20
Run-time dependency x11 found: YES 1.6.9
Run-time dependency xi found: YES 1.7.10
Run-time dependency xtst found: YES 1.2.3
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Build targets in project: 3

Found ninja-1.10.0 at /usr/bin/ninja
ninja install -C "build/release"
ninja: Entering directory `build/release'
[4/12] Compiling C object 'src/25a6634@@xclicker@exe/xclicker-app.c.o'.
FAILED: src/25a6634@@xclicker@exe/xclicker-app.c.o 
cc -Isrc/25a6634@@xclicker@exe -Isrc -I../../src -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -O3 -Wno-incompatible-pointer-types -pthread -MD -MQ 'src/25a6634@@xclicker@exe/xclicker-app.c.o' -MF 'src/25a6634@@xclicker@exe/xclicker-app.c.o.d' -o 'src/25a6634@@xclicker@exe/xclicker-app.c.o' -c ../../src/xclicker-app.c
../../src/xclicker-app.c: In function ‘xclicker_app_init’:
../../src/xclicker-app.c:13:31: error: parameter name omitted
   13 | static void xclicker_app_init(XClickerApp* /*app*/)
      |                               ^~~~~~~~~~~~
[10/12] Compiling C object 'src/25a6634@@xclicker@exe/mainwin.c.o'.
ninja: build stopped: subcommand failed.
make: *** [Makefile:44: release] Error 1

x@y:~/development/temp/xclicker$ 
`

**Comment by robiot** [comment]
You need a newer gcc version. Otherwise use the precompiled ones

**Comment by TTorai** [comment]
Thank you,
it compiles and works now.
Upgraded Linux Mint to 21 Vanessa, now with gcc 11.4.0.
Executable now is nearly 10% smaller in bytes.

Best regards.

**Comment by robiot** [comment]
Thanks, I hope it works well for you!
