### ISSUE TITLE
Feature request: Conditional clicking

### ISSUE THREAD

**Issue by SteegHobland** [robiot/xclicker#103]
I'd like to see an easy-to-use conditional autoclicker for Linux, but I haven't found one yet. One that can detect events, and then react to them.

Would you add that sort of feature set to your project?

Even if you ultimately decide not to, thank you for considering the request.

**Comment by robiot** [comment]
Cool idea but I think it’s out of scope. If you wanna do something like this, it would be easier to just make a script
