### ISSUE TITLE
dotnet

### ISSUE THREAD

**Issue by Bomlex** [robiot/xclicker#14]
does not work with dotnet games/software
tested on manajro and arch

**Comment by robiot** [comment]
Do you mean games ran with wine / proton?

**Comment by Bomlex** [comment]
yes wine / proton. 
but now i just tried the terraria linux version, clicker doesn't work because of dotnet, I guess

**Comment by robiot** [comment]
Try with xdotool
```
xdotool click 1
```
If that doesn't click in wine/proton, it's a wine/proton problem and I probably can't do much about it.

**Comment by pegasusearl** [comment]
Yes `xdotool click 1` doesn't work on Terraria. It's the native Terraria linux version that I tested.

**Comment by Bomlex** [comment]
sorry I completely forgot to answer. 
I tried with/without  a delay but it barely worked.. out of 100 maybe 5 were clicked and only when I hold down LMB myself... is a bit strange 

later I made a "speed clicker" macro for keyboard/mouse (on windows) rebooted to linux.. it worked but very slowly... and so macro is not an option

**Comment by pegasusearl** [comment]
> Have you also tested with both modes in the XClicker settings? With / Without XEvent

Yes.
----

I found that a tool named Evemu will work for Terraria. It's not as convenient as xdotool though. Need root access and gotta manually select input devices.
https://fedoramagazine.org/simulate-device-input-evemu/

**Comment by Bomlex** [comment]
> Have you also tested with both modes in the XClicker settings? With / Without XEvent

that was the first thing i tried.
but have you already tried, do you have the same issues?

**Comment by robiot** [comment]
> > Have you also tested with both modes in the XClicker settings? With / Without XEvent
> 
> that was the first thing i tried. but have you already tried, do you have the same issues?

My Proton and Wine is kinda broken right now, but as fast as I fix it, I will try to fix the problem.

**Comment by a7md8762** [comment]
robiot do u have discord?
i wanna talk to u

**Comment by robiot** [comment]
> robiot do u have discord? i wanna talk to u

@a7md8762 Yes robiot#3455

**Comment by robiot** [comment]
![Peek 2022-03-21 18-46](https://user-images.githubusercontent.com/68228472/159316004-90c5c5a3-6d3f-4ac7-bb58-909a4650f04a.gif)

Works perfectly fine for me!
(Why it isn't switching between On/Off in the wine application in top left, is because it is a failed autoclicker that starts autoclicking on a toggle button which basically disables it 🤦)

Adding a native mode would we awesome tho, with udev. Then it also would work in Wayland

**Comment by robiot** [comment]
Closing this now.
If you believe this is a mistake, please reopen it.
