### ISSUE TITLE
Feature: Add ability to click and hold

### ISSUE THREAD

**Issue by rossmaclean** [robiot/xclicker#18]
It would be nice to be able to specify a duration, and have it keep the mouse clicked for that duration each click "cycle".
Might also be nice to have the ability to hold down the mouse button continuously.

**Comment by Pysis868** [comment]
That would be nice.  Without looking into the program more, I was able to add a custom shortcut in the keyboard settings area of my Linux GNOME desktop which executes this command: `xdotool mousedown 1`

I determined 1 is the primary button, where 3 was the secondary button, using this command: `xev | grep button`

**Comment by StevenAlexander44** [comment]
This works on gnome? It doesnt work on ubuntu

**Comment by Pysis868** [comment]
```
> neofetch os kernel de wm
os: Linux 
kernel: 5.15.14-200.fc35.x86_64 
de: GNOME 41.3 
wm: Mutter 
```

**Comment by StevenAlexander44** [comment]
ah well i meant to say xubuntu- uses xfce4 not gnome

**Comment by a7md8762** [comment]
anyone have the owner of this repo discord?

**Comment by ctxnop** [comment]
I proposed a patch to provide this features. See the corresponding [pull request](https://github.com/robiot/xclicker/pull/22).

**Comment by robiot** [comment]
This is now partially implemented. If you belive the PR by ctxnop didn't fix what you wished for, please make a new issue!

**Comment by ctxnop** [comment]
Maybe it worth to make a release out of it so that distros can update their packages.
