### ISSUE TITLE
Click X amount of times

### ISSUE THREAD

**Issue by vadi2** [robiot/xclicker#20]
Thanks for the great Linux app!

Is it possible to click a certain amount of times, so I can press the button once instead of twice (on/off)?

**Comment by robiot** [comment]
Yes, enable "Repeat Only" and put in how many times you want it to click there. Once it clicked that amount of times, It will automatically stop.

**Comment by vadi2** [comment]
Oh, I thought "repeat only" stood on it's own without a connection to value.
