### ISSUE TITLE
Suggestion - Flathub (Flatpak) Installation Support

### ISSUE THREAD

**Issue by dginovker** [robiot/xclicker#23]
Currently the two [offered](https://xclicker.xyz/downloads) installation methods are .AppImage and .Deb (which are both fantastic), but being added to Flathub means easier installation for a variety of installations. Flathub additionally has some pretty awesome [auto-update](https://github.com/flathub/com.visualstudio.code.insiders/commits/beta) features.

**Comment by dginovker** [comment]
Relevant Flathub discourse post: https://discourse.flathub.org/t/flatpak-request-xclicker-autoclicker/2350

**Comment by robiot** [comment]
Thanks! I will look into it as fast as possible.

**Comment by robiot** [comment]
Hm. I can't really figure out how to make a flatpak nor how they work just yet. It seems pretty annoying to update the flatpak too when creating a new release, so the auto update would be great.

**Comment by robiot** [comment]
Here we go. Now its just waiting left to do https://github.com/flathub/flathub/pull/2937

**Comment by dginovker** [comment]
@robiot They have some feedback on the PR

**Comment by robiot** [comment]
@dginovker Yeah saw that. I have replied many days ago ,but I forgot I had to press submit review for the comments to send :facepalm:

**Comment by robiot** [comment]
Now I have fixed everything. So as fast as they notice it, it will hopefully get merged :)

**Comment by robiot** [comment]
Finally it's all done.

https://github.com/flathub/xyz.xclicker.xclicker
https://flathub.org/apps/details/xyz.xclicker.xclicker (may take some time before it shows up)
