### ISSUE TITLE
ARMv7 Support

### ISSUE THREAD

**Issue by mollthecoder** [robiot/xclicker#24]
Possibly provide binaries for ARMv7 architecture? That would be very useful.

**Comment by robiot** [comment]
Yes. I am thinking about setting up github actions or something to build assets when I create a release (Deb, AppImg, SomeArmPackage)

**Comment by mollthecoder** [comment]
> Yes. I am thinking about setting up github actions or something to build assets when I create a release (Deb, AppImg, SomeArmPackage)

That's a good idea.

**Comment by robiot** [comment]
This is now implemented. It now builds for arm, aarch64 and amd64 automatically with github actions!!!
I don't have an arm machine right now, so could you test it and tell me if it worked?

**Comment by robiot** [comment]
> The problem for me is that ARMv7 is 32-bit and those files are 64-bit, it appears. Sorry.

There is for both 32bit(arm)and 64bit(aarch)
The one you should be using is the one only called arm. Test that one.

**Comment by mollthecoder** [comment]
```
dpkg: error processing archive xclicker_1.3.2_arm.deb (--install):
 package architecture (arm) does not match system (armhf)
Errors were encountered while processing:
 xclicker_1.3.2_arm.deb
```

**Comment by mollthecoder** [comment]
Here's a uname:
`Linux raspberrypi 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux`

**Comment by robiot** [comment]
> ```
> 
> dpkg: error processing archive xclicker_1.3.2_arm.deb (--install):
> 
>  package architecture (arm) does not match system (armhf)
> 
> Errors were encountered while processing:
> 
>  xclicker_1.3.2_arm.deb
> 
> ```

Oh yes, its arch arm in the dpkg when it should be armhf. I will change it asap. For now, use the appimage

**Comment by mollthecoder** [comment]
Yes, it works wonderfully now.
