### ISSUE TITLE
Hold mode that is running while hotkey is held down

### ISSUE THREAD

**Issue by robiot** [robiot/xclicker#28]
I think we misunderstood the hold feature that was requested. Currently it just holds down the button without sending a MouseUp event until stop is pressed. If there is anyone that uses this mode as it is right now, please let me know and for what.

**Comment by userbyte** [comment]
I do not use the hold mode that is currently implemented, however I would find it very useful to have an option for the auto-clicking to run when the hotkey is held. I'd much appreciate this feature!

**Comment by robiot** [comment]
@userbyte This is now implemented!

**Comment by BananaViking** [comment]
@robiot please dont change this mode I like it the way it is, I use this for whenever I need to hold my left click for a long duration to do something in a game, Normally my hands is in so much pain when I need to left click to be pressed down for a long duration, this has helped to relief so much of the pain.

**Comment by robiot** [comment]
@BananaViking This mode, and the old one will stay, I promise. You can now switch between them in the `Hotkey` dropdown under Options.

**Comment by userbyte** [comment]
> @userbyte This is now implemented!

Awesome! Thanks so much ♥
