### ISSUE TITLE
Feature request, not a bug. Requesting extra input options. 

### ISSUE THREAD

**Issue by user624264835** [robiot/xclicker#33]
I am using version 1.3.2 and do not see any features for this so I ask if you could make this software work with other inputs as well? For example, letters and numbers on the keyboard? Or maybe even controller input? I would also like to request an option for more than one input to be pressed at once as well (with the option of separate times in which the inputs are pressed.) I also suggest adding a save-able config for different presets you want to use. Thanks!

![1](https://user-images.githubusercontent.com/96346186/163038248-ef3aa9ab-421e-4b9b-a3a7-61f6c114f509.png)

![2](https://user-images.githubusercontent.com/96346186/163038261-c5b06849-e166-401d-bd01-2496594c15b9.png)

**Comment by robiot** [comment]
I will close this for now since it's very generalized and does not provide a clear description of enchantments.
