### ISSUE TITLE
Allow binding of Left/Right clicks

### ISSUE THREAD

**Issue by BananaViking** [robiot/xclicker#56]
Hello
I am loving xclicker and I was wondering if you could allow left/right click as key binds to activate the auto clicker.
Also if possible a hotkey to suspend the program so the key bind doesn't activate the auto clicker.

Thanks so much for your hard work.

edit: i dont know how to add labels to my post, sorry.

**Comment by robiot** [comment]
Hey, thanks for the issue. This is related to #12, but it isn't very clear. I'll change the issue title for that one.
