### ISSUE TITLE
Remember all options after restart

### ISSUE THREAD

**Issue by Mrarthtato** [robiot/xclicker#57]
Please add the ability to remember hold or normal settings every time XClicker reopens

**Comment by robiot** [comment]
It would be better to remember everything in this case.

**Comment by Mrarthtato** [comment]
Ya that would be great actually!

**Comment by paul-onof** [comment]
Is there a way to keep the 'hold' option by editing `~/.config/xclicker.conf` please ?

For now, this file contains this :

```
[Options]
USE_XEVENT=false
BUTTON1=-1
BUTTON2=49
```

**Comment by RayBTA** [comment]
still waiting for it
