### ISSUE TITLE
Unable to Start or Change keybind on Fedora 36 KDE

### ISSUE THREAD

**Issue by BananaViking** [robiot/xclicker#61]
#### OS / ENVIRONMENT:
 * Operating system: Fedora 36 KDE
 * De or Wm: KDE
 * XClicker version: 1.4.0

#### STEPS TO REPRODUCE:
1.Download Appimage
2.make into an executable then double click to execute
3.Attempt to start the auto clicking with default hotkey, Nothing happens.
4.Attempt to change the default hotkey, turns out i am unable to rebind it to any key at all ( i tried pretty much every key)

#### EXPECTED BEHAVIOUR:

On hotkey press start the auto clicker, and on start to change keybind  it should register the key im pressing to turn it into the new hotkey
#### ACTUAL BEHAVIOUR:

When pressing the default hotkey (f8) the auto clicker doesnt do anything, and when i try to change the default hotkey it doesnt register any of the keys i press to change it into.
#### Additional information (optional):
I see this when i attempt to follow this guide https://github.com/robiot/xclicker/wiki/Installation#other-distros
![image](https://user-images.githubusercontent.com/106994788/177008590-77d7e6ea-a640-4ca6-82b2-32f1943c2d35.png)

edit: im very new to linux so go easy on me plz

**Comment by robiot** [comment]
Are you on wayland or xorg? https://unix.stackexchange.com/questions/202891/how-to-know-whether-wayland-or-x11-is-being-used

**Comment by BananaViking** [comment]
![image](https://user-images.githubusercontent.com/106994788/177010242-7e5f6ee6-794b-4378-96c4-f36681fa4d9b.png)
Wayland according to the commands that i followed in the link

**Comment by robiot** [comment]
XClicker is for x11, as it name states **X**clicker. If you wan't it to work, you'll need to run xorg/x11. To run kde with x11 you'll need to:
1. Log out. so you go to your login screen
2. Press the desktop session button and change it from `Desktop Session: Plasma (Wayland)` to `Desktop Session: Plasma (x11)`

**Comment by BananaViking** [comment]
Thanks so much for your help and and i apologize for making such  a mistake.
I really appreciate your time and help

one small thing that can be ignored, when i rename the file it wont launch, its probably another thing that im missing. <3
