### ISSUE TITLE
Doesn't Run

### ISSUE THREAD

**Issue by Thonkman** [robiot/xclicker#62]
### ISSUE TYPE:
 - Bug Report

#### OS / ENVIRONMENT:
 * Operating system: Manjaro 5.15
 * De or Wm:
 * XClicker version:

#### STEPS TO REPRODUCE:
1. Download xclicker using any method
2. try making
3. fails

#### EXPECTED BEHAVIOUR:
should download and be runnable

#### ACTUAL BEHAVIOUR:
fails to download due to /home/user/xclicker/PKGBUILD: line 17: make: command not found

**Comment by robiot** [comment]
You wil need to install the base-devel package. Without it, you can't do much with pkgbuilds at all.

pacman -S base-devel

**Comment by Thonkman** [comment]
Thanks a ton!
