### ISSUE TITLE
Cant remove/uninstall in Fedora 37

### ISSUE THREAD

**Issue by wevertondevt** [robiot/xclicker#65]
How to remove/uninstall this project using procedure:
```
git clone https://github.com/robiot/xclicker.git
cd xclicker
make install

```

I'm trying to remove it with `make uninstall` and I have the error `make: *** No rule to process the 'uninstall' target`, I've tried to remove it in other ways using commands to remove the directory completely but without success.

**Comment by robiot** [comment]
Oh interesting, seems like I forgot to add the uninstall rule.
For now use these commands
```
sudo rm ./usr/bin/xclicker
sudo rm /usr/share/applications/xclicker.desktop
sudo rm ./usr/share/pixmaps/xclicker.png
```

Also, since you are using fedora, the best way to download it is with flatpak.
