### ISSUE TITLE
Infinite warning windows

### ISSUE THREAD

**Issue by q00u** [robiot/xclicker#68]
### ISSUE TYPE:
 - Bug Report

#### OS / ENVIRONMENT:
 * Operating system: Ubuntu 22.04 LTS
 * De or Wm: ??
 * XClicker version: 1.4.0

#### STEPS TO REPRODUCE:
1. Run XClicker, safe mode on
2. Set time to 10 ms
3. Press F8 to start

#### EXPECTED BEHAVIOUR:
A window to pop up saying "Warning: Intervals under 100 milliseconds are restricted because of safe mode."

#### ACTUAL BEHAVIOUR:
INFINITE such windows appeared. Close and close and close and they never close. They're open two at a time. Right-click icon in taskbar and "Quit 2 windows" (only 2 because the main window has long been closed), and two more pop up.

**Comment by q00u** [comment]
No, I didn't hold F8 down, lol. I don't know what to tell you. I'm back on Ubuntu 20.04 LTS due to other problems with 22.04, so I can't recreate the same _exact_ environment anymore.

**Comment by EEKIM10** [comment]
I am able to repro this
[Peek 2023-07-07 23-46.webm](https://github.com/robiot/xclicker/assets/53234499/8c2130ed-6084-43f8-ab22-34f718af1463)

I'm using arch linux with KDE Plasma on X11, latest git build. I pressed no keys during this recording.

**Comment by robiot** [comment]
This should be fixed by #85
