### ISSUE TITLE
add ability to execute autoclicker on startup with it clicking

### ISSUE THREAD

**Issue by wrighttoby** [robiot/xclicker#69]
Hi, i am planning to make an afk roblox account in a game 24/7 on a vm to try it out. then i will put all the software on my rpi2 however there is an issue so when i hook it up to power and internet i CANNOT get the autoclicker to run by itself on startup. i am using a platform to help me host the 24/7 account called now.gg since i have to have the site open actively i cannot have the autoclicker failing on me could you add the capability please

**Comment by robiot** [comment]
Currently XClicker doesn't have the capability to do that, but you could use [xdotool ](https://github.com/jordansissel/xdotool) for thtat.

**Comment by robiot** [comment]
Closing as out of scope as of now.
