### ISSUE TITLE
Key still in use after exit

### ISSUE THREAD

**Issue by RonnyBarthmann** [robiot/xclicker#82]
i used xclicker with the default hotkey of "f8"

and after i closed it i am no longer able to use the f8 key

everytime i press f8 the current window lose the focus while i press f8, no other window has the focus and when i release the f8 key everythink is normal again ... until i use f8 again

this behavior still remains after restart, even i dont run xclicker again after the boot process

i am using Kubuntu 22.04 LTS without wayland (just the good old X-server)

**Comment by robiot** [comment]
Could you send a screenshot of the xclicker settings you were using so I could try to replicate it?

**Comment by RonnyBarthmann** [comment]
![Screenshot_20230816_161101](https://github.com/robiot/xclicker/assets/32592152/4a73e5c2-ad55-4d40-99c4-24718bb96afe)
