### ISSUE TITLE
Crash when setting the hotkey

### ISSUE THREAD

**Issue by UrsoTriangularo** [robiot/xclicker#83]
When i opened my xclicker today, it crashed whenever i tried to set the hotkeys, after some debugging i noticed it was happening because **g_idle_add** expects a function that returns a boolean, and removes the function from the event list if it returns false, instead, it was receiving a void function, which would cause it to run indefinitely, causing a segmentation fault.

It can be fixed by replacing **g_idle_add** with **g_idle_add_once**.

Im not sure why it suddenly started happening, maybe a GLib update changed the behavior of g_idle_add?

**Comment by UrsoTriangularo** [comment]
Probably related issue: #68

**Comment by Shringe** [comment]
Same here

**Comment by Shringe** [comment]
Do you know where I could change 'g_idle_add' with 'g_idle_add_once'?

**Comment by robiot** [comment]
Yeah, I think I was able to repro it. I will see if I can fix it.

**Comment by robiot** [comment]
Ok seems like it isnt building in cicd anymore, supposedly because that is some kind of new glib function??. Maybe I just should use g_idle_add and return false.

**Comment by robiot** [comment]
Ok I made a fix, im waitig for it to build,,, pls work

**Comment by robiot** [comment]
cool it built, 1.5.0 is released
