### ISSUE TITLE
Debian ARM64 Dependency

### ISSUE THREAD

**Issue by tinya** [robiot/xclicker#84]
### ISSUE TYPE:
 - Bug Report

#### OS / ENVIRONMENT:
 * Operating system: Ubuntu LTS 22.04.3 LTS Guest (VM) running on M2 Mac Sonoma 14.0 Host
 * De or Wm: GNOME
 * XClicker version: 1.4.0

#### STEPS TO REPRODUCE:
```
tinya@ubuntu:~$ sudo apt-get install ~/Downloads/xclicker_1.4.0_aarch64.deb 
[sudo] password for tinya: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'xclicker:aarch64' instead of '/home/tinya/Downloads/xclicker_1.4.0_aarch64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 xclicker:aarch64 : Depends: libx11-6:aarch64 but it is not installable
                    Depends: libxi6:aarch64 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

#### EXPECTED BEHAVIOUR:
Successful installation of .deb file.

#### ACTUAL BEHAVIOUR:
Installation attempt will throw unmet dependency errors.

#### Additional information (optional):
Not a Linux expert by any means but this appears to stem from Debian architecture nomenclature: https://wiki.debian.org/SupportedArchitectures
https://wiki.debian.org/Arm64Port#Nomenclature_and_defines

`Architecture` specified in the `control` file: https://github.com/robiot/xclicker/blob/c4a7efc28f662378b058a47165d05b49cd70cc6b/pkg/deb/control#L6

```
Architecture: aarch64
```

To get this to install correctly, I unpackaged the .deb and control archive, edited the architecture to `arm64`, and repackaged the files:

```
tinya@ubuntu:~/Downloads$ cat control | grep Arch
Architecture: arm64
tinya@ubuntu:~/Downloads$ tar --ignore-failed-read -cvJf control.tar.xz control
tinya@ubuntu:~/Downloads$ ar rcs xclicker_1.4.0_arm64.deb debian-binary control.tar.xz data.tar.xz 
```

**Comment by robiot** [comment]
So the problem is that debian doesnt recognize aarch64 and arm64 as the same thing?. Should we just change aarch64 to arm64?
