### ISSUE TITLE
hey

### ISSUE THREAD

**Issue by Yhnoone** [robiot/xclicker#88]
### ISSUE TYPE:
 - Bug Report

#### OS / ENVIRONMENT:
 * Operating system:
 * De or Wm:
 * XClicker version:

#### STEPS TO REPRODUCE:
1.
2.
3.

**Comment by robiot** [comment]
hello xD

is there any bug you want to report 😆 ?

**Comment by Yhnoone** [comment]
no

**Comment by robiot** [comment]
Lol ok
