### ISSUE TITLE
Proposal for a feature to simulate clicking on multiple coordinates in a sequence

### ISSUE THREAD

**Issue by HarshGuptaShorthillsAI** [robiot/xclicker#96]
Proposal for a feature to simulate clicking on multiple coordinates in a sequence 

An auto clicker which enables to click in a sequence at different coordinates. We can limit the number of clicks in one pattern, and maybe charge a premium amount too for people who want extra clicks 
(A contribution has been made but i suppose UI should remain the same.)

**Comment by robiot** [comment]
It's possible, but for this I think creating a simple batch script that calls xdotool would be better personally.
```bash
#!/bin/bash
# Batch script to click on coordinates in sequence using xdotool

# Array of coordinates (x, y)
coordinates=(
    "100 200"
    "200 300"
    "300 400"
    "400 500"
    "500 600"
)

# Loop through each coordinate and perform a click
for coord in "${coordinates[@]}"; do
    # Extract x and y from the coord variable
    x=$(echo $coord | awk '{print $1}')
    y=$(echo $coord | awk '{print $2}')
    
    # Move the mouse to the x, y coordinates
    xdotool mousemove $x $y

    # Click at the current mouse position
    xdotool click 1

    # Optional: wait for a second before moving to the next coordinate
    sleep 1
done
```
