### ISSUE TITLE
Can't bind key

### ISSUE THREAD

**Issue by CreeperAndi** [robiot/xclicker#98]
### ISSUE TYPE:
 - Bug Report

#### OS / ENVIRONMENT:
 * Operating system: Nobara 39 linux
 * De or Wm:
 * XClicker version: almost every version tried

#### STEPS TO REPRODUCE:
1.download 
2.open(with gearlever in my case)
3.try to bind custom key to activate clicking - just says "Press Desired Keys" and if i do nothing happens, "reset preset options" also doesn't work
 
but i somehow bound it to w, but don't know how and can't rebind it

![Screenshot_20240506_194106](https://github.com/robiot/xclicker/assets/152625618/4fa36531-8a9e-42de-9baa-00834d3ee367)

**Comment by hexahigh** [comment]
Having the same issue after switching from X11 to wayland.
