### ISSUE TITLE
I cant change my start bind

### ISSUE THREAD

**Issue by Jarren547** [robiot/xclicker#99]
<!---
1. When i try to change the bind to start it says press desired key but if i press anything nothing happens 
please fix this bug/issue

### ISSUE TYPE:
 - Bug Report
![Screenshot 2024-07-07 6 01 58 PM](https://github.com/robiot/xclicker/assets/174969348/5b4036f8-3df2-430a-92ae-c6064c758ba8)

**Comment by Jarren547** [comment]
Sorry i did not write anything anyways i tried to change the start bind from f8 to s but it just says press the desierd key and if i press any key nothing happens (i dont use f8 or any function key because im on a chromebook)

**Comment by robiot** [comment]
Are you using xorg or wayland? Because XClicker is only supported on xorg.

**Comment by Jarren547** [comment]
how do i know which one im using?

**Comment by robiot** [comment]
@Jarren547 You can open a terminal and type
```
 echo $XDG_SESSION_TYPE
```

Send me whatever that outputs.

**Comment by Jarren547** [comment]
it say 1,23
in the lower right corner what does that mean

**Comment by Jarren547** [comment]
it says 1,23 in the lower right coner what does that mean?

**Comment by Jarren547** [comment]
it says wayland is there a way to change it to xorg

**Comment by CreeperAndi** [comment]
> Are you using xorg or wayland? Because XClicker is only supported on xorg.     Thats so sad😕

**Comment by robiot** [comment]
@CreeperAndi I know, but it's due to how Wayland is built. 

In Xorg there are global APIs to emulate mouse clicks, get cursor position, global keyboard presses and so on. But Wayland does not implement such functions. :/

**Comment by robiot** [comment]
@Jarren547 Yes, when you sign in there should be an option to change to Gnome on Xorg, or KDE on xorg.

It depends which DE you are using. I would recommend searching it up.

**Comment by linuxgaming** [comment]
I just wanted to add that xclicker does work on wayland but only with xorg apps running through xwayland (which conveniently include steam and most, if not all, games). So you can change the start key in ~/.config/xclicker.conf if needed (use `wev` to read your desired key's code and set it as BUTTON2, the default F8 has code 74), and then use it as usual.

You can also try running other apps through xwayland if you need to use xclicker on them, for example:
MOZ_ENABLE_WAYLAND=0 firefox

**Comment by samson510** [comment]
i just installed and works great after 2 hours of using im on gnome wayland  46.4 version under arch  full amd pc  both xwayland and native wayland works

**Comment by Jarren547** [comment]
how do i change it

**Comment by robiot** [comment]
> how do i change it

I already said it in a comment above 😭

**Comment by Jarren547** [comment]
when i sign into what

**Comment by robiot** [comment]
When you sign into your system @Jarren547
